### ISSUE TITLE
karakterweb.no kræsjer ved søk på ukjent emne/årstall

### ISSUE THREAD

**Issue by pergpau** [HermanNygaard/Karakterweb-CLI#1]
karakterweb.no fryser og man kan ikke gjøre flere søk uten refresh hvis du gjør følgende:
- Søk etter en kombinasjon av emne og årstall som ikke eksisterer

Da loader den for evig og man kan heller ikke gjøre andre søk.

Testet i Chrome og Firefox.

PS. Takk for at du laget karakterweb.no! Veldig nyttig :)

**Comment by HermanNygaard** [comment]
Hei!

Takk for issuen. Ser ut som at API'en til NSD hadde endret respons på ugyldige søk, det skal bli håndtert riktig nå på https://karakterweb.no
